# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  test:
    name: GradleTest
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'STAGING')

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Grant Permissions to gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Test
      run: ./gradlew test --tests "*"

    - name: Test Success
      if: success()
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ github.token }}
        script: |
          const pull_number = "${{github.event.number}}"
          await github.pulls.createReview({
            ...context.repo,
            pull_number,
            body: "All tests passed.",
            event: "APPROVE"
          })
    - name: Test Fail
      if: failure()
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ github.token }}
        script: |
          const pull_number = "${{github.event.number}}"
          await github.pulls.createReview({
            ...context.repo,
            pull_number,
            body: "There is something wrong with test codes.",
           event: "REQUEST_CHANGES"
          })
          await github.pulls.update({
            ...context.repo,
            pull_number,
            state: "closed"
          })

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
